# Generated by Django 4.1.3 on 2022-11-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_student_ongoing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoing',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='ongoing',
            old_name='student_id',
            new_name='student',
        ),
    ]
