# Generated by Django 4.1.3 on 2022-11-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_assingment_assignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='assingment',
            new_name='assignment',
        ),
        migrations.AddField(
            model_name='problem',
            name='lecture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.lecture'),
            preserve_default=False,
        ),
    ]
