# Generated by Django 4.1.2 on 2022-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_problem_reference_alter_problem_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='created_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(auto_created=True),
        ),
    ]
