# Generated by Django 4.1.3 on 2022-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_code_created_date_alter_solution_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
