# Generated by Django 4.1.3 on 2022-11-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_code_created_date_alter_solution_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='product.assignment'),
        ),
    ]
