# Generated by Django 4.1.3 on 2022-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_problem_idx_alter_code_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='skeleton',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
