# Generated by Django 4.1.3 on 2022-11-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_problem_skeleton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='reference',
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('reference_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.problem')),
            ],
        ),
    ]
